### ISSUE TITLE
Add Functionality to "Search For a Class By Pathway!" Button

### ISSUE THREAD

**Issue by anderm18** [anderm18/HASSPathways#10]
This is a bit of a longer one, but it'll really solidify your understanding of Vue. 

Head over to https://hasspathways.com/admin-portal. Click on "Search For a Class By Pathway!". Notice in your URL box of your browser it doesn't take you anywhere. This is because it has yet to be implemented. Your Job is as follows:

Display all of the Pathways in a nice List OR Grid (up to you really!). When a user clicks the pathway, display all of the courses in this pathway in a similar way. This will require a Combination of Vue, HTML, and CSS.

When a user clicks on a Course you've listed, take them to the page to edit that particular course. See how Ryan implemented it for Search for Course to edit by course code section (button to the right of Search for Class by Pathway).

This is a long one, so partial commits are cool! I.e. if you only want to list out all the pathways, another person wants to list out courses, and someone else comes along and redirects to the edit page for each course.

Good Luck!

**Comment by Ryzon3** [comment]
I didn't even realize this was an issue you made. I am tackling this already. I started it a bit last semester and have almost finished up a quick mock up for it.

**Comment by anderm18** [comment]
all good haha I'm just trying to stay organized since we have more people : )
