### ISSUE TITLE
Checkboxes in the course cards display themselves above the footer

### ISSUE THREAD

**Issue by liuj-42** [anderm18/HASSPathways#133]
You can see it clipping here: 
![brave_ZOtgqYgCpV](https://user-images.githubusercontent.com/65922029/181183307-34583af5-5098-40f0-9d10-bb0121d484ba.png)

**Comment by michaelni678** [comment]
Is this already fixed? Can't seem to replicate the issue

**Comment by Ryzon3** [comment]
Same as Michael I cannot replicate issue. Closing it for now unless someone can replicate it.
