### ISSUE TITLE
Deleting all classes in a pathway doesn't remove the pathway on the "My HASS Pathways" page

### ISSUE THREAD

**Issue by liuj-42** [anderm18/HASSPathways#14]
Picture below shows just an empty pathway with courses selected for it, you have to manually delete it after removing all classes for the pathway. 

![firefox_hrrCfkaYSj](https://user-images.githubusercontent.com/65922029/170422060-a74b6357-6d75-48a9-837f-3c8f85a365be.png)

**Comment by anderm18** [comment]
Issue still open after merge
