### ISSUE TITLE
Add functionality to tabs for courses offered "Upon instructor availability" (after multiyear scrapper is done)

### ISSUE THREAD

**Issue by michaelni678** [anderm18/HASSPathways#140]
**(for when the multi-year scrapper is completed)**

Add functionality to UIA (upon instructor availability) tabs when courses are listed as "offered upon instructor availability". 
In the linked pull is where I made the actual tabs so you know what files the stuff is in: https://github.com/anderm18/HASSPathways/pull/138

![image](https://user-images.githubusercontent.com/82001942/181823399-047ec304-ec2c-460d-a494-c20cdf14768c.png)
The thingie circled in the image above should light up when classes are listed as "offered upon instructor availability", just like classes that are listed as offered in spring, summer, fall, etc.

**Comment by Ryzon3** [comment]
Was fixed in #138
