### ISSUE TITLE
Move our Netlify Instance over to an S3 bucket on AWS

### ISSUE THREAD

**Issue by anderm18** [anderm18/HASSPathways#18]
Netlify is really nice to us, however, it's becoming more and more difficult to work with what we're trying to accomplish in the admin portal. So, if we can migrate this instance over to S3, that would be great. 

Clone the latest version of the project and create an S3 Bucket on the HASS Pathways AWS instance. Build the the latest version in your console with:
 ```bash 
npm run build
```
Then, push all the build to your created S3 bucket. Make sure to make the files of the S3 bucket publicly accessible by all so that people can actually access the site. Then, test your solution by visiting the hosted S3 bucket.

WARN: If you would like to complete this issue, I need to authorize you to our AWS Console. Please contact me (michael) directly so I can create an IAM user for your AWS account on ours. If you need help with the logistics of AWS, also please reach out : )

**Comment by RafaelCenzano** [comment]
Changed to deploying via gh actions to gh pages.
