### ISSUE TITLE
2022-2023 Course Prereqs Undefined

### ISSUE THREAD

**Issue by WitherKNyx** [anderm18/HASSPathways#181]
This seems isolated to 2022-2023/courses.json, but there are some courses which have known prerequisite courses, but the prerequisites are empty.

**Comment by Ryzon3** [comment]
This issue is due to how the XML was formatted for 2022-2023. PreReqs and crosslisted are now pop ups when clicked which makes them different in the XML from the scraper. To fix this prereqs and crosslisted cannot use "field text" anymore.

**Comment by WitherKNyx** [comment]
I've made some adjustments to the course scraper, it seems to now correctly read most courses that have prereqs.
