### ISSUE TITLE
Create subtle buttons to cycle between Graph Selection and current Tabular Selection

### ISSUE THREAD

**Issue by anderm18** [anderm18/HASSPathways#21]
Title says it all, create button that will show the courses in either the (current) tabular representation, or the (future) Graphical Representation. This way, the student can choose their preferred method.

Obviously, if nothing has been created for this new Interface yet, your graph button should redirect nowhere (for now)

**Comment by Ryzon3** [comment]
I created a component at the start of last semester where the graph view should sit. Feel free to have the page render that component or the course table component
