### ISSUE TITLE
Finish the graph view component

### ISSUE THREAD

**Issue by Ryzon3** [anderm18/HASSPathways#23]
The graph view component has almost no code written within it. We want this view to be equal with the tabular view in terms of how much information it contains at the very least.
I would suggest tackling this with several commits so a few people can work on it.

Currently the plan was to use the vue-diagrams potentially, but there might be a better option.

**Comment by liuj-42** [comment]
working on doing graph stuff but not using the component atm
you can see what im doing on the branch graph-view

**Comment by Ryzon3** [comment]
Going to close this issue since we have the graph view working using a different method.
