### ISSUE TITLE
"dark mode on" and "dark mode off" are switched on hover

### ISSUE THREAD

**Issue by CryptidGrrrl** [anderm18/HASSPathways#30]

**Comment by Bowserinator** [comment]
Ideally, the text would be changed to what the button does, ie "Switch to light mode" instead of "Dark mode off" which as of rn is a bit confusing

**Comment by dicosn** [comment]
Why not have the icons match the current mode as well? As of right now, you see the sun while in dark mode, and the moon when in light mode. What if you see the moon while using dark mode, and when you hover over the moon icon, it transitions to the sun icon, and vice versa with the sun in light mode?
