### ISSUE TITLE
Hass Pathways logo is unreadable in light mode 

### ISSUE THREAD

**Issue by CryptidGrrrl** [anderm18/HASSPathways#31]
This should be an easy fix, likely will involve just inverting the colors of the logo and switching the logo image depending on dark/light mode

**Comment by Bowserinator** [comment]
Alternatively, make the navbar color the primary (red) color so the logo stands out, this would also make the light mode navbar less boring

**Comment by dimitri-lopez** [comment]
Added two different logos that get displayed depending on the current mode. See `frontend/src/assets/dark-mode-logo.png` and `frontend/src/assets/light-mode-logo.png`.
