### ISSUE TITLE
Allow Admin to specify if course is 1st, 2nd, or 3rd level course when editing

### ISSUE THREAD

**Issue by anderm18** [anderm18/HASSPathways#33]
Doing some backend work for the Admin Portal, realized there's no way to specify which course category the course they are editing falls under. This is critical as we won't know where to send that data on the backend.

Basically, redesign the course editing section to include an option for each compatible pathway to specify first, second, or third course. 

I may just end up doing this myself, but I figured if any entry level wanted to give it a shot I'd post it here. Please self-assign if you're going to take it up : )

**Comment by Ryzon3** [comment]
Do note we aren't going to be using the 1st, 2nd, 3rd format in the future for the JSON. We are changing to a one of, required, remaining style for the JSON see the [Quacs Data](https://github.com/quacs/quacs-data/blob/master/hass_pathways.json) for the format.
