### ISSUE TITLE
When you select a course in the Tabular Menu, have it automatically shift you to Course 2, then from course 2

### ISSUE THREAD

**Issue by anderm18** [anderm18/HASSPathways#5]
Go to https://hasspathways.com/pathway?pathway=artificial_intelligence, and click on a course. We want to make it so when you click on your course, you are slid over to 2nd course and prompted to select your 2nd course, and then from 2nd course to 3rd. Basically, make it so you don't have to click on 2nd course to get to it after you select your first course!

**Comment by Bowserinator** [comment]
But what if you want to select multiple "course 1" options? Then you'll have to go back to Tab 1 every time you click a course

**Comment by anderm18** [comment]
This was a Bram suggestion, so that is a good point to bring up. Whomever picks up this issue please keep that in mind

**Comment by dimitri-lopez** [comment]
Added the feature as well as a toggle. The buttons don't look the best but the feature is there and can easily be added/removed as needed in the future.
