### ISSUE TITLE
Obtain the communication intensive data for the courses scraper

### ISSUE THREAD

**Issue by Ryzon3** [anderm18/HASSPathways#53]
In the file `backend\scrapers\courses_scraper.py` the `obtain_CI` function needs to be completed. This will be quite the task since to my knowledge there is no information for communication intensive on the catalog. This means either we need to write a quick script to navigate to the course on SIS and check if the course has the CI attribute, or we could utilize another projects data to obtain this.

Either way without this we will not have the data for communication intensive unless we implement this.

**Comment by Ryzon3** [comment]
Temporarily was fixed using CI data from Bram. This data is not a future proof way, so better way would still be better.

**Comment by dimitri-lopez** [comment]
Closed via 7c3973b. Added an SIS scraper
