### ISSUE TITLE
mobile home page add margin between buttons

### ISSUE THREAD

**Issue by michaelni678** [anderm18/HASSPathways#68]
![image](https://user-images.githubusercontent.com/82001942/174865355-3b325dc9-07a7-4aa8-89a2-b07d24319348.png)

**Comment by Ryzon3** [comment]
I just checked over a PR that seemed to fix this, but it now seems to be broken again post merge, so I am opening it back up for now..

**Comment by dimitri-lopez** [comment]
Fixed by a commit I made earlier today. See 644999620fdd3408f99db3a791adb7461fbd3c7b.
