### ISSUE TITLE
Add vertical space between buttons on home page

### ISSUE THREAD

**Issue by ACE3R2** [anderm18/HASSPathways#77]
It is a little cramped between the "Find pathways from classes" and "Admin and secure portal buttons"; add some spacing between them.
![image](https://user-images.githubusercontent.com/90933282/175322116-ae6f9d0b-ea0b-46e1-b64b-6bf772c856e3.png)

**Comment by dimitri-lopez** [comment]
Fixed by a commit I made earlier today. See 644999620fdd3408f99db3a791adb7461fbd3c7b.
