### ISSUE TITLE
Fix color of "Search for Class by Pathway!" Button on Admin Portal

### ISSUE THREAD

**Issue by anderm18** [anderm18/HASSPathways#9]
Navigate to https://hasspathways.com/admin-portal

See how the "Search for Class by Pathway!" button is a different color from the rest? Fix that!

**Comment by ACE3R2** [comment]
Some later commit has fixed this issue - 
![image](https://user-images.githubusercontent.com/90933282/175855939-088231c0-a500-4ebb-b189-70e01b4d7253.png)
(at least, they don't look different to me), so I'm closing this.
